gokarna-theme/gokarna-hugo

- themes/gokarna/layouts/partials/head.html
- themes/gokarna/layouts/partials/header.html
- themes/gokarna/static/css/main.css
This is the base structure. We can make minor modifications later :)
> Add right side of the header

- themes/gokarna/layouts/_default/list.html
- themes/gokarna/layouts/_default/single.html
- themes/gokarna/layouts/partials/head.html
- themes/gokarna/layouts/partials/header.html
- themes/gokarna/static/css/main.css
* Add posts page
* Add `normalize.css`
* Improve html tags
> Basic posts page

- themes/gokarna/layouts/_default/baseof.html
- themes/gokarna/static/css/main.css
Check commit titles for more info
> Footer & Header fixes

- exampleSite/content/posts/first_post.md
- exampleSite/content/posts/second_post.md
- themes/gokarna/layouts/index.html
- themes/gokarna/layouts/partials/head.html
- themes/gokarna/static/css/dark.css
- themes/gokarna/static/css/main.css
* Homepage (centered avatar)
* Replace `Roboto` with `Quicksand-Medium` for font
* Add letter spacing for content to look more readable
* Post page layout - better spacing
> Fix Homepage, website font and post page layout

- themes/gokarna/static/css/dark.css
- themes/gokarna/static/css/main.css
> Change tag colors

- exampleSite/content/posts/first_post.md
- themes/gokarna/static/css/dark.css
- themes/gokarna/static/css/main.css
> Add table styling and color pallets

- themes/gokarna/layouts/_default/baseof.html
- themes/gokarna/layouts/partials/header.html
- themes/gokarna/layouts/partials/post.html
- themes/gokarna/static/css/dark.css
- themes/gokarna/static/css/main.css
- themes/gokarna/static/js/main.js
* Support for description on post page
* Tag post count color fixed (fixed on hover too)
* Added border-top to footer (got accidentally removed?)
* Mobile: 
* removed opacity on hamburger menu
* (color) on nav-link fixed
* theme toggle working
* Show date in a better way
* Tag counts overlap the hamburger menu
* Fixed white flash when using the website on phone in dark mode
> UI fixes - mobile and tags

- static/css/main.css
* Increase font size
* Decrease footer font size (slightly)
* Fix spacing between headings
Check preview. IMO this looks better
> Visual changes to prettify post page

- static/js/main.js
> Use Id instead of query selector to fix number string. Fixes #97

- static/css/main.css
> Remove left padding from container CSS

- layouts/partials/list.html
Fixing the mismatched opening and closing header tags.
> Fix header tag

- i18n/de.toml
- i18n/en.toml
- i18n/es.toml
- layouts/_default/terms.html
Added Spanish internationalization. I had to make the "Tags" page title string translatable and updated the English and Deutsch entries accordingly.
> Add Spanish translation

- layouts/_default/baseof.html
- layouts/index.html
- layouts/partials/head.html
- layouts/partials/header.html
Fixes: https://github.com/526avijitgupta/gokarna/issues/193
> Allow http/https url for avatar

- exampleSite/content/posts/theme-documentation-basics.md
> fixes: #165 | removed "releases" from documentation 

- exampleSite/content/posts/theme-documentation-advanced.md
documentation updated for #190
> documentation updated #190

- exampleSite/config.toml
- exampleSite/content/posts/theme-documentation-basics.md
- layouts/partials/list-posts.html
- layouts/partials/post.html
> Change date format #135

- assets/css/main.css
fixes #156 
long footer would wrap instead of going over TOC
> long footer fixed

- exampleSite/content/posts/theme-documentation-basics.md
Fix outdated basics documentation filename. More info at https://github.com/526avijitgupta/gokarna/issues/216
@yashmehrotra Please review and merge if it looks good
> Update theme-documentation-basics.md (fixes #216)

- assets/js/main.js
- layouts/_default/baseof.html
- layouts/index.html
- layouts/partials/head.html
- layouts/partials/header.html
- layouts/partials/list-posts.html
- Remove type=text/javascript
- Change duplicate IDs to classes
- Add blank alt text to SVG social icons
- Change section to div
- Remove trailing slashes from link, img
- Change article to div
This fixes the warnings and errors from https://validator.w3.org/nu/?doc=https%3A%2F%2Fgokarna-hugo.netlify.app%2F and https://validator.w3.org/nu/?doc=https%3A%2F%2Fgokarna-hugo.netlify.app%2Fposts
The deploy preview contains no errors or warnings: https://validator.w3.org/nu/?doc=https%3A%2F%2Fdeploy-preview-218--gokarna-hugo.netlify.app and https://validator.w3.org/nu/?doc=https%3A%2F%2Fdeploy-preview-218--gokarna-hugo.netlify.app%2Fposts
> Fix Nu Html Checker warnings and errors

- exampleSite/config.toml
- exampleSite/content/posts/theme-documentation-basics.md
- layouts/partials/back-to-top.html
- layouts/partials/page.html
- layouts/partials/post.html
Pulled the code out of `post.html` so it can be used a partial in `page.html` *and* `post.html` :grinning:
> refactor: make backToTop button usable on pages

- exampleSite/config.toml
- exampleSite/content/posts/theme-documentation-basics.md
Add `GitInfo` (Hugo) and `dateFormat` (Gokarna) documentation.
> docs(exampleSite): add GitInfo & dateFormat

- README.md
@526avijitgupta Changed the README to have an unordered list instead of numbered.
Also, added @jamesericdavidson in a newly created contributors section (will retroactively added past major contributors as well)
> chore: add majorly active contributors on readme

- .github/FUNDING.yml
Add github sponsors with buy me a coffee profile linked
> feat: add github sponsors

- README.md
Fetched top contributors from: https://github.com/526avijitgupta/gokarna/graphs/contributors
> chore: update major contributors list with past contributors

- layouts/partials/header.html
Closes #259 
- ~~structured data validator~~ needs account
> refactor: pass lighthouse SEO audits

- .github/workflows/screenshot.yml
- Containerfile
- screenshot.py
@526avijitgupta @jamesericdavidson FYI
> chore: add auto screenshot update worklow

- layouts/partials/header.html
> Bugfix: I accidentally replaced .Site.Title with .Title in #279

- i18n/fr.toml
Hello.
Very nice theme, thank you for developing this.
I've translated all the i18n strings to French :)
> add french translations

- README.md
Closes #286
Happy holidays! @526avijitgupta @yashmehrotra 
And congrats on almost 400 stars
> docs(readme): mention translations

- README.md
List translations in their own language first
> chore(readme): add native language names

- static/svg/icons/x.svg
Add social media icon X (Twitter rebrands to X).
> Add social network X icons

- README.md
> chore(readme): add russian translation

- archetypes/default.md
- archetypes/posts.md
Closes #254
https://github.com/gohugoio/hugo/issues/12940
> fix(archetypes): add timezone to date

- README.md
> chore(readme): mention bt-pr translation

- .github/workflows/stale-bot.yml
Fixes: #337 
@jamesericdavidson Please review this as well
> chore: add stale issue bot

- assets/css/dark.css
> chore: use dark tertiary color for <hr>
