gokarna-theme/gokarna-hugo

- static/css/dark.css
- static/css/main.css
I updated the social icon links on the dark theme and removed the padding on the code blocks. I noticed the issue with the code blocks when showing multiple lines in a recent post.
> Fix social icons on dark theme. Fixes #78

- static/css/main.css
Just noticed that the homepage posts box was a little skewed in alignment and width. Also made sure it's still responsive
Before:
After:
> Fix homepage width and alignment of posts

- exampleSite/config.toml
- exampleSite/content/posts/theme-documentation-advanced.md
Following the [katex docs](https://katex.org/docs/autorender.html) I have added inline math support with single `$` to the gokarna docs. 
Closes #101
> Added inline math to docs following katex docs

- exampleSite/config.toml
After seeing #107 , I thought that placing Feather icons in the menu would be another welcome addition.
I acknowledge that Gokarna is a minimal theme, but my rationale for submitting this PR is that there is a consistent use of icons - including the social icons and avatar - making the Home, Posts, Projects and Tags menu items stand out by their omission.
No offence taken if you decline this PR. Cheers!
> Add Feather icons to exampleSite menu

- layouts/_default/terms.html
Hello, I've started using this theme and I noticed that in case no tag is present yet, the page is left empty.
Thought would have been nice not to leave the page empty.
This PR adds just a phrase to tell visitors that there are no tags.
> Add view for empty tags

- layouts/partials/header.html
- static/css/main.css
- static/js/main.js
The dark theme toggle button is currently unreacheable by screen readers (programs blind people use to access the internet).
This adds a target for them, along with some invisible text, matching the state of the icon.
Improvement suggestions welcome.
> Add screen reader support to dark theme button.

- README.md
- exampleSite/config.toml
- layouts/index.html
- layouts/partials/header.html
The img avatar in the header already sets alt to "avatar" for screen readers. In most cases, this is enough, however a user may desire a more descriptive alt text. This makes the attribute configurable by the user to make the theme more accessible for blind users since the avatar can now have a description custom-tailored to the desired image, for example a logo with text or a photo of a person or place. Since the img in header.html and index.html pull from the same source, this parameter is applied to both. If the parameter is not set, the alt text will simply default to "avatar" on both. This change is not visible on-screen and will only affect those using screen-reading software.
> Added configurable alt text to the avatar

- layouts/partials/header.html
Similarly to the issue with screen readers not finding the dark mode 
toggle button, the mobile view menu button was also unreacheable. This is 
event worse, because it means a blind user is likely to not even know 
there's a menu, when browsing on a phone or with a narrow browser window 
on desktop.
This change fixes the issue the same way.
> Add invisible screen reader target to mobile menu button.

- layouts/partials/post.html
Including a `/` prefix on a call to https://gohugo.io/functions/abslangurl/ prevents it from correctly adding any custom prefixes.
Fixes #129 and #126
> Remove prefixed / from tag link on post page

- layouts/index.html
Using `rel=me` on a hyperlink indicates that its destination represents the same person or entity as the current page. Mastodon suggests adding it to verify our presence on the platform establishing a bi-directional rel-me link.
Context http://microformats.org/wiki/relme
Based on https://github.com/luizdepra/hugo-coder/pull/195
> add rel option for social media icons

- exampleSite/content/posts/theme-documentation-basics.md
- layouts/partials/post.html
- layouts/partials/prev-next.html
- static/css/main.css
Sadly, works poorly with `.Weight` due to Hugo's default sort, which prefers `.Weight` over `.Date`:
- https://gohugo.io/variables/page/#page-variables
- https://gohugo.io/templates/lists#default-weight--date--linktitle--filepath
This workaround does not seem to work either: https://www.feliciano.tech/blog/custom-sort-hugo-single-pages/
If you think this is worth adding, I can look into using `.Date` instead of Hugo's default sort.
I'd also appreciate feedback on the CSS, as I'm no designer.
> Add Previous and Next buttons

- static/css/main.css
Fixes #128 
Long date strings like "September 22, 2022" can be wider than the 20% of the width allocated to them, causing the date to wrap around on the posts page.
The width of the post title is lowered from 80% to 73%, the highest width where wrapping never occurs before the mobile CSS breakpoint is hit.
> Shrink the post title width to allow wider dates

- i18n/de.toml
- i18n/en.toml
- layouts/404.html
- layouts/_default/terms.html
- layouts/index.html
- layouts/partials/prev-next.html
This PR adds the possibility to translate the hardcoded strings within the template to different languages. German translation is included as example (and for my personal use). Other languages can be added by creating the corresponding files within the folder /i18n.
> add i18n strings and german translation

- layouts/partials/post.html
The title says it all. If the `disqusShortname` is set for the site, render it for all posts!
> Render Disqus comments if set

- layouts/index.html
Adding `aria-label` (according to lightouse report) should increase accessibility.
> Add a11y labels on social links

- layouts/partials/footer.html
A very small change to only show the copyright message when the `footer` parameter is set.
> Only show footer when set

- layouts/_default/terms.html
- layouts/index.html
In the Netlify deployment preview the icons do not show up because of CORS. They were served from the old site, because the `BaseURL` is not set correct. This is fixed by using relative links.
> Change all links to be relative

- assets/js/main.js
Extracting the theme toggling into a separate function.
**Background:** I use [fireship-io/flamethrower](https://github.com/fireship-io/flamethrower) as a routing and prefetching utility in my page. On every navigation the event listeners were added to the toggle element. by using the option `capture: true` this does not happen anymore.
It does not brake code with this option, although I'll understand that this can be seen as a tailored solution for my problem. Feel free to close this PR with a wont-fix and I will keep it as my personal fork.
Yet I still think it improves readability.
> Attach event listener with options

- layouts/partials/header.html
This PR allows specifying nav menu links to be opened in a new tab.
Config:
```toml
[[menu.main]]
identifier = "github"
url = "https://github.com/zerodahero"
weight = 4
pre = "<span data-feather='github'></span>"
[menu.main.params]
newPage = true
```
Will open the "github" link in a new tab (depending on browser behavior).
If there's an easier way than going through the params, that might be nice as well. I think the  "official" Hugo approach may be to use a `rel = external` param for the menu item--happy to go that route as well if that's more widely understood.
> Add new-page param for target=blank

- assets/css/dark.css
- assets/css/main.css
- exampleSite/config.toml
- exampleSite/content/posts/theme-documentation-basics.md
- layouts/partials/post.html
> fixed #155: back to top button

- exampleSite/config.toml
- exampleSite/content/posts/theme-documentation-advanced.md
- layouts/partials/post.html
fixes #123 
Uses https://utteranc.es/ to allow comments on posts via GitHub issues. 
**Files amended:**
- `config.toml` to add site params 
- `post.html` to add js code 
**preview:** https://gokarna.mansoorbarri.com
> comments added 

- assets/css/main.css
Verified on the same device. Footer looks fine now
> Increase footer width if toc is not visible, fixes #205

- assets/css/main.css
On mobile, all nav links are presented in a hamburger menu. Because this menu uses different CSS classes, some styling for svg icons next to the links was missing and making them look not as great. The icons are off-center and very thin.
This PR adds the same CSS snippet to the links in a hamburger menu.
> Fix link icon styling on mobile

- assets/css/main.css
- assets/js/main.js
Currently, clicking on a link in the table of contents smoothly scrolls the page to the relevant section. For some reason, the URL hash wasn't updated by this though. 
Smooth scrolling is currently implemented in JS. Luckily, there is a single CSS property `scroll-behavior: smooth`, that automatically enables smooth scrolling for all hash links. This PR exchanges the current implementation for this single property.
> Fix smooth scrolling not changing URL hash

- layouts/partials/post.html
When ShowBackToTopButton is false, the button itself is removed. But the script implementing the button is still running and throwing an error, because it cannot find the expected button element.
This PR removes the script as well as the button, if the setting is turned off
> Fix JS error when ShowBackToTopButton is false

- layouts/partials/page.html
- layouts/partials/post.html
The original template caused the content to be nested inside a pair of p tags (for instance, try viewing the source of https://gokarna-hugo.netlify.app/posts/lorem-ipsum/ vs the fixed version at https://deploy-preview-210--gokarna-hugo.netlify.app/posts/lorem-ipsum/), which causes my browser and the Nu HTML checker to complain about a stray `</p>` tag
> Don't wrap {{ .Content }} with p tags

- assets/css/main.css
On iOS, the font sizing is inconsistent in long code blocks. According to this [comment](https://github.com/adityatelange/hugo-PaperMod/issues/828#issuecomment-1171994855), this is an issue with iOS. This PR implements the solution suggested by [bglw](https://github.com/bglw).
I have tested this on my own site and it works as expected.
Before:
After:
> Fix inconsistent font sizing in code blocks on iOS

- assets/js/main.js
Hello there!
When the theme loads, it always sets either dark or light mode depending on the OS setting and immediately stores it in local storage. Meaning, if a user initially visits a site in the night, it will be dark forever or until changed by clicking on the icon. And vice versa.
This is a confusing behavior, this patch changes the logic - until the icon is clicked and setting explicitly set by a user, it follows the OS. The change is simple - local storage is not written on page request.
To test this feature:
* Delete webpage local storage settings via browser functionality.
* Visit the page in dark OS setting.
* Visit the page in light OS setting.
* The theme should follow until the "bulb" icon is clicked.
> Keep using auto theme when unset explicitly

- layouts/partials/post.html
I have fixed the following warning:
```
WARN  deprecated: .Site.DisqusShortname was deprecated in Hugo v0.120.0 and will be removed in a future release. Use .Site.Config.Services.Disqus.Shortname instead.
```
> Fix ".Site.DisqusShortname was deprecated in Hugo v0.120.0".

- layouts/partials/prev-next.html
Custom date format was implemented in #203 but still not applied to prev-next post section.
This PR apply custom date format for them.
> Apply custom date format to prev-next.html

- layouts/partials/post.html
Since `scroll-behavior: smooth` is applied in #213 , back to top button didn't work in Google Chrome.
This is a known issue that Chrome calls `requestAnimationFrame` in every tick.
https://stackoverflow.com/questions/73052119/scroll-behavior-smooth-doesnt-work-on-html-in-chrome
I think there is no need call `smoothScrollToTop` function and just calling `window.scrollTo` is fine, because we already have `scroll-behavior: smooth`.
> Fix back to top button not working

- exampleSite/content/posts/theme-documentation-advanced.md
- layouts/partials/post.html
Tags can be used to categorize posts, and categories don't need to be displayed.
An example is if the pages are used for about-us and contact, and posts as blog articles and projects presentation. Example of hugo.toml using this new field:
[params]
hiddenTags = ["project", "blog"]
[menu]
[[menu.main]]
identifier = "projects"
url = "/tags/project/"
name = "My Projects"
weight = 1
[[menu.main]]
identifier = "blog"
url = "/tags/blog/"
name = "Blog"
weight = 2
> All tags listed in hiddenTags aren't displayed on the posts.

- layouts/partials/header.html
The links added to the menu were missing spaces between their attributes. It's now present, making the HTML compliant.
This time it's done on one line, my replacing {{- by {{. It seems the dash is a space controller.
> Add a space between HTML attributes in header

- exampleSite/content/posts/theme-documentation-advanced.md
- layouts/partials/list-posts.html
- layouts/partials/post.html
Based on how the posts are used (e.g. to describe projects or blog posts), it can be useful to hide the date or the description. Using the fields `params.tagsHidePostDate` and
`params.tagsHidePostDescription`, it's possible.
> Hide some informations about the posts

- layouts/index.html
- layouts/partials/head.html
There has three changes:
1. Limit description length as 160 charactors for SEO.
2. Fixed issue of icon url not found if socialIcons name in different case.
> Optimize pages meta description and index page  social icon

- exampleSite/content/posts/theme-documentation-advanced.md
- layouts/partials/footer.html
tl;dr Implementation for #222.
- Pages which are *not* of kind `page` continue to use `now.Year`
- Pages which do *not* declare `.Date` also use `now.Year`
- Pages which declare `.Date` use it *instead* of `now.Year`
- Pages which declare `.Lastmod` and `.Date` use both dates in a range, *instead* of `now.Year`
A long `copyright` string will overflow the `.footer` container, ergo some assistance on the CSS side would be greatly appreciated. :smiley: 
N.B. Copyright is described by Hugo here: https://gohugo.io/methods/site/copyright/
-  ~~config opt-in *?*~~
~~`copyright` is only displayed if it exists in `config.toml`; I'd argue this isn't necessary~~
- ~~add `dateFormat` to `config.toml` *?*~~
- ~~add `Lastmod` to any relevant `exampleSite` pages for illustration *?*~~
> feat: display accurate copyright years on pages

- exampleSite/content/posts/theme-documentation-advanced.md
- exampleSite/content/posts/theme-documentation-basics.md
- layouts/partials/footer.html
`footer` and `copyright` can include Markdown syntax. As mentioned in the docs:
> This is best used for including hyperlinks, emoji, or text formatting.
Screenshot example:
N.B. I omitted this during testing (#233) and forgot to re-implement. Apologies :grin:
> feat: markdownify footerText

- exampleSite/content/posts/theme-documentation-basics.md
- i18n/de.toml
- i18n/en.toml
- i18n/es.toml
- i18n/pl.toml
- layouts/index.html
I've added simple customization for number of posts on homepage.
Also I've added Polish translation and I've fixed translation for "Recent Posts/Posts" header on homepage. This modification is backward compatible, but one can replace translation to replace "Posts" (for `popular` posts) with "Popular posts" or anything one want.
> Option for number of posts on homepage, Polish translation

- i18n/de.toml
- i18n/en.toml
- i18n/es.toml
In previous pull-request #240 I've put incorrect translation keys in i18n files.
> fix: Proper names of keys for translated 'Posts' title on posts' list

- archetypes/posts.md
- exampleSite/content/posts/theme-documentation-basics.md
Implement some basic [Hugo front matter](https://gohugo.io/content-management/front-matter/#fields), and [custom Gokarna front matter](https://gokarna-hugo.netlify.app/posts/theme-documentation-advanced/#content-types), to make life more convenient for [`hugo new` users](https://gokarna-hugo.netlify.app/posts/theme-documentation-basics/#d-create-your-first-post).
Following [Hugo's lookup order](https://gohugo.io/content-management/archetypes/#lookup-order):
- `default.md` applies to `content/`
- `posts.md` applies to `content/posts/`
N.B. Archetypes follow the YAML syntax already laid out in the docs.
- `lastmod` is *not* rendered when its value is equal to `date`
- `lastmod` is present in `default.md` as the year affects the `footerText` Scratch
- tests
Expected behaviour. When `lastmod` …
> feat(archetypes): add default front matter

- assets/css/dark.css
- assets/css/main.css
- layouts/index.html
As suggested by @jamesericdavidson, I am submitting a PR to fix #238.
The `EasyList – Social Widgets` filter was blocking the `##.social-icons-list` class, preventing social media icons from appearing. To fix this, I have simply renamed all instances of `social-icon` to `gk-social-icon` (`gk` = Gokarna).
With this change, the social media links should now display correctly, even when aggressive ad blockers are enabled.
> Fix: `socialIcons` disappear when ad blockers are enabled.

- layouts/_default/terms.html
- layouts/index.html
Fix for some links in case of hosting page from non-root path like https://example.com/blog
> fix: Relative links for non-root hosting

- exampleSite/config.toml
- exampleSite/content/posts/theme-documentation-advanced.md
Reduce exampleSite's HTML file size:
- Home page reduced by ~3.1k
- Emoji Support reduced by ~67k
N.B. [The hosted version of `exampleSite`](https://gokarna-hugo.netlify.app/) is not minified:
> feat(config): minify exampleSite HTML output

- layouts/index.html
This resolves #255, and builds on #249. #249 fixed non-root hosting (#237), but broke alternate-domain hosting. I believe moving from `absUrl` to `relUrl` solves both issues (including making sure the social icons work on the Netlify deploy previews for this repo!).
Would appreciate review from @pkierski as author of #249.
> Use relUrl for SVG injection

- assets/css/main.css
- layouts/index.html
- layouts/partials/header.html
> refactor: pass lighthouse accessibility audits

- assets/js/main.js
- layouts/partials/header.html
Code is messy, but works.
Ignore emulated performance :roll_eyes:
> fix: mobile lighthouse accessibility

- layouts/_default/baseof.html
- layouts/partials/head.html
- layouts/partials/header.html
- layouts/partials/list-posts.html
- layouts/partials/page.html
- layouts/partials/post.html
- layouts/partials/prev-next.html
I noticed that some of my posts have ' in their titles which don't get properly converted into &rsquo; HTML smart quotes, so I passed all occurrences of `.Title` through `markdownify` to fix that.
> Markdownify titles

- layouts/partials/post.html
The user should not be expected to add `Date format` in config, if it is not added, it should fallback to default
> fix: handle missing date format fallback

- exampleSite/content/posts/theme-documentation-advanced.md
- exampleSite/content/posts/theme-documentation-basics.md
#291 fixed the breakages present when the (removed) conditions were not met
> docs: remove dateFormat warnings

- assets/css/main.css
- assets/js/main.js
- exampleSite/config.toml
Tested locally (bluesky icon being directly rendered from wikimedia url):
> fix: External svgs not rendering in top nav bar

- exampleSite/content/posts/theme-documentation-basics.md
Update the docs for #295 to follow the patterns established in #243:
- List the **Font size** heading alphabetically
- Add link to explain the `font-size` CSS property
- Use default value in the code snippet
@526avijitgupta @yashmehrotra
> docs(basics): update fontSize

- exampleSite/content/posts/theme-documentation-basics.md
- layouts/partials/post.html
display estimated reading time before date (like Medium.com)
https://gohugo.io/methods/page/readingtime/
> feat(post): add .ReadingTime

- exampleSite/content/posts/theme-documentation-basics.md
- layouts/partials/post.html
For consistency with other configuration keys, the value should be a boolean (not a string).
> refactor(post): eval togglePreviousAndNextButtons as a bool

- assets/css/main.css
- exampleSite/content/posts/theme-documentation-advanced.md
- exampleSite/content/posts/theme-documentation-basics.md
- layouts/index.html
re-implement #119 - the Hugo way of displaying front matter - without breaking index-about.md (#179)
https://gohugo.io/content-management/organization/#index-pages-_indexmd
if _index.md exists (and has content), print it
else, if index-about.md exists (without checking for file contents), print it
> refactor(index): support _index.md

- assets/js/main.js
> chore: svg border

- assets/css/main.css
set position to a value other than absolute or fixed: https://developer.mozilla.org/en-US/docs/Web/CSS/position
> fix(css): long footerText can overlap Markdown content

- assets/css/main.css
Reverts gokarna-theme/gokarna-hugo#327
> Revert "fix(css): long footerText can overlap Markdown content"

- exampleSite/content/posts/theme-documentation-advanced.md
- layouts/partials/page.html
- layouts/partials/post.html
allows H1 to be defined separately from the page title
> feat: add h1 param to front matter

- layouts/index.html
External social media links on the homepage open in new tabs.
- Added `target="_blank"` and `rel="noopener noreferrer"` to social media links while preserving custom `rel` attributes.
> Open social media links on homepage in new tabs

- assets/css/main.css
- layouts/partials/prev-next.html
Fixes a bug in which the footer was overlapping with the previous/next post navigation links on posts when only one navigation button was present (e.g., on the most recent post where no "next" button exists).
Changes:
- Wrapped the entirety of `prev-next.html` in a container, and added clearfix to the container to properly contain the floated elements.
- Reduced body margin on blog posts when post navigation is present. The global body's `margin-bottom: 170px;` was creating excessive space between the navigation and footer on blog posts. A targeted rule reduces this to `80px` to maintain consistent spacing while accounting for floated post navigation elements.
- Increased the space between post content and post navigation for visual consistency.
> Fix footer overlap issue on blog posts with navigation

- exampleSite/content/posts/theme-documentation-basics.md
- layouts/partials/head.html
improve accessibility by using (r)em units:
https://developer.mozilla.org/en-US/docs/Web/CSS/font-size#pixels
https://fedmentor.dev/posts/font-size-px/
> refactor: don't declare font-size in px
